// <auto-generated />
using System;
using FiveThreeOne.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FiveThreeOne.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260223181202_MakeExerciseTableNamePlural")]
    partial class MakeExerciseTableNamePlural
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FiveThreeOne.Domain.Entities.AssistanceExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxRepsAmount")
                        .HasColumnType("integer");

                    b.Property<int>("MinRepsAmount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WorkoutId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("AssistanceExercises");
                });

            modelBuilder.Entity("FiveThreeOne.Domain.Entities.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("FiveThreeOne.Domain.Entities.MainExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("MainExercises");
                });

            modelBuilder.Entity("FiveThreeOne.Domain.Entities.MainExerciseSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MainExerciseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Percentage")
                        .HasColumnType("integer");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("MainExerciseId");

                    b.ToTable("MainExerciseSets");
                });

            modelBuilder.Entity("FiveThreeOne.Domain.Entities.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("FiveThreeOne.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("BenchOneRP")
                        .HasColumnType("real");

                    b.Property<float>("BenchTM")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("DeadliftOneRP")
                        .HasColumnType("real");

                    b.Property<float>("DeadliftTM")
                        .HasColumnType("real");

                    b.Property<float>("MilitaryPressOneRP")
                        .HasColumnType("real");

                    b.Property<float>("MilitaryPressTM")
                        .HasColumnType("real");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("SquatOneRP")
                        .HasColumnType("real");

                    b.Property<float>("SquatTM")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FiveThreeOne.Domain.Entities.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HighestTM")
                        .HasColumnType("integer");

                    b.Property<Guid>("MainExerciseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Week")
                        .HasColumnType("integer");

                    b.Property<int>("WorkoutNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MainExerciseId");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("FiveThreeOne.Domain.Entities.AssistanceExercise", b =>
                {
                    b.HasOne("FiveThreeOne.Domain.Entities.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FiveThreeOne.Domain.Entities.Workout", null)
                        .WithMany("AssistanceExercises")
                        .HasForeignKey("WorkoutId");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("FiveThreeOne.Domain.Entities.MainExercise", b =>
                {
                    b.HasOne("FiveThreeOne.Domain.Entities.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("FiveThreeOne.Domain.Entities.MainExerciseSet", b =>
                {
                    b.HasOne("FiveThreeOne.Domain.Entities.MainExercise", null)
                        .WithMany("MainExerciseSets")
                        .HasForeignKey("MainExerciseId");
                });

            modelBuilder.Entity("FiveThreeOne.Domain.Entities.Workout", b =>
                {
                    b.HasOne("FiveThreeOne.Domain.Entities.MainExercise", "MainExercise")
                        .WithMany()
                        .HasForeignKey("MainExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainExercise");
                });

            modelBuilder.Entity("FiveThreeOne.Domain.Entities.MainExercise", b =>
                {
                    b.Navigation("MainExerciseSets");
                });

            modelBuilder.Entity("FiveThreeOne.Domain.Entities.Workout", b =>
                {
                    b.Navigation("AssistanceExercises");
                });
#pragma warning restore 612, 618
        }
    }
}
